### ISSUE TITLE
When saving new listing, new error: ActiveRecord::AssociationTypeMismatch - ListingAvailability

### ISSUE THREAD

**Issue by joycemap** [joycemap/JoyceStay#13]
ActiveRecord::AssociationTypeMismatch - ListingAvailability(#70351374301020) expected, got ["start_date", ""] which is an instance of Array(#70351359123580):
  app/controllers/api/listings_controller.rb:5:in `create'

**Comment by carolineartz** [comment]
https://github.com/joycemap/JoyceStay/pull/19

**Comment by joycemap** [comment]
PR 19 fixed the issue!
