### ISSUE TITLE
When editing a listing, the start date and end date cannot be edited.

### ISSUE THREAD

**Issue by joycemap** [joycemap/JoyceStay#4]
Start date and end date cannot be edited.
 Not sure if it is a front-end or back end issue. I did see in the listing_form.jsx (lines 495 and 508) that there were "readonly" values. 

<img width="1004" alt="Screen Shot 2020-06-25 at 10 15 24 PM" src="https://user-images.githubusercontent.com/57893220/85736842-6b516b80-b731-11ea-85cc-0bca3b177805.png">

**Comment by joycemap** [comment]
Figured out after reading naima's code that the "readonly" means that, after the calendar dates are selected, the values are populated back into the fields. No direct entry in the field seem to be saved. Both hese date formats are rejected as direct entry into the date: YYYY-MM-DD, MM/DD/YYYY

**Comment by carolineartz** [comment]
this PR addresses this https://github.com/joycemap/JoyceStay/pull/20
