### ISSUE TITLE
Edit the default values for: HomeType, Max guests

### ISSUE THREAD

**Issue by joycemap** [joycemap/JoyceStay#6]
In the add new listing page:

- require photos of location , 
- change default for home type from Entire Home to "Select a ...", 
- change default of max guests = 0

**Comment by 1Maria** [comment]
require home type and max guests to be changed 
require amenities (or none) to be selected

**Comment by joycemap** [comment]
All fields are now required fields, but the red "error" line around those fields are not displayed together with the error messages.

**Comment by joycemap** [comment]
Workaround implemented by displaying which fields have errors.  Issue closed by PR 21
